apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: profile-service:latest
          ports:
            - containerPort: 50054
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_ADDRESS
