apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-blue
  labels:
    app: auth-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
      version: blue
  template:
    metadata:
      labels:
        app: auth-service
        version: blue
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50050
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: SERVER_HTTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_HTTP_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_GRPC_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_SWAGGER_ADDRESS
