version: '3.9'

services:
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - SERVER_ADDRESS=0.0.0.0:50051
    networks:
      - awesome-messenger

  profile-service:
    build:
      context: ./services/profile
      dockerfile: Dockerfile
    ports:
      - "50054:50054"
    environment:
      - SERVER_ADDRESS=0.0.0.0:50054
    networks:
      - awesome-messenger

  friend-service:
    build:
      context: ./services/friend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8080
    networks:
      - awesome-messenger

  message-service:
    build:
      context: ./services/message
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - SERVER_ADDRESS=0.0.0.0:50052
    networks:
      - awesome-messenger

  notification-service:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    environment:
      - SERVER_ADDRESS=0.0.0.0:50053
    networks:
      - awesome-messenger

  search-service:
    build:
      context: ./services/search
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_ADDRESS=0.0.0.0:8081
    networks:
      - awesome-messenger

networks:
  awesome-messenger:
    driver: bridge