version: '3.9'

services:
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "50000:50000"
      - "8000:8000"
      - "8081:8081"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8000
      - SERVER_SWAGGER_ADDRESS=localhost:8001
      - SERVER_GRPC_ADDRESS=0.0.0.0:50000
    networks:
      - awesome-messenger

  friend-service:
    build:
      context: ./services/friend
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
      - "8011:8011"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8010
      - SERVER_SWAGGER_ADDRESS=localhost:8011
    networks:
      - awesome-messenger

  message-service:
    build:
      context: ./services/message
      dockerfile: Dockerfile
    ports:
      - "50020:50020"
      - "8020:8020"
      - "8021:8021"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8020
      - SERVER_SWAGGER_ADDRESS=localhost:8021
      - SERVER_GRPC_ADDRESS=0.0.0.0:50020
    networks:
      - awesome-messenger

  notification-service:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    ports:
      - "50030:50030"
      - "8030:8030"
      - "8031:8031"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8030
      - SERVER_SWAGGER_ADDRESS=localhost:8031
      - SERVER_GRPC_ADDRESS=0.0.0.0:50030
    networks:
      - awesome-messenger

  profile-service:
    build:
      context: ./services/profile
      dockerfile: Dockerfile
    ports:
      - "50040:50040"
      - "8040:8040"
      - "8041:8041"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8040
      - SERVER_SWAGGER_ADDRESS=localhost:8041
      - SERVER_GRPC_ADDRESS=0.0.0.0:50040
    networks:
      - awesome-messenger

  search-service:
    build:
      context: ./services/search
      dockerfile: Dockerfile
    ports:
      - "50050:50050"
      - "8050:8050"
      - "8051:8051"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8050
      - SERVER_SWAGGER_ADDRESS=localhost:8051
      - SERVER_GRPC_ADDRESS=0.0.0.0:50050
    networks:
      - awesome-messenger

networks:
  awesome-messenger:
    driver: bridge