version: '3.9'

services:
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "50050:50050"
      - "8080:8080"
      - "8081:8081"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8080
      - SERVER_SWAGGER_ADDRESS=localhost:8081
      - SERVER_GRPC_ADDRESS=0.0.0.0:50050
    networks:
      - awesome-messenger

  friend-service:
    build:
      context: ./services/friend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:8090
      - SERVER_SWAGGER_ADDRESS=localhost:8091
    networks:
      - awesome-messenger

  message-service:
    build:
      context: ./services/message
      dockerfile: Dockerfile
    ports:
      - "50060:50060"
      - "9000:9000"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:9000
      - SERVER_GRPC_ADDRESS=0.0.0.0:50060
    networks:
      - awesome-messenger

  notification-service:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    ports:
      - "50070:50070"
      - "9010:9010"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:9010
      - SERVER_GRPC_ADDRESS=0.0.0.0:50070
    networks:
      - awesome-messenger

  profile-service:
    build:
      context: ./services/profile
      dockerfile: Dockerfile
    ports:
      - "50080:50080"
      - "9020:9020"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:9020
      - SERVER_GRPC_ADDRESS=0.0.0.0:50080
    networks:
      - awesome-messenger

  search-service:
    build:
      context: ./services/search
      dockerfile: Dockerfile
    ports:
      - "50090:50090"
      - "9030:9030"
    environment:
      - SERVER_HTTP_ADDRESS=0.0.0.0:9030
      - SERVER_GRPC_ADDRESS=0.0.0.0:50090
    networks:
      - awesome-messenger

networks:
  awesome-messenger:
    driver: bridge