apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-blue
  labels:
    app: notification-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
      version: blue
  template:
    metadata:
      labels:
        app: notification-service
        version: blue
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50053
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SERVER_ADDRESS
