apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
    version: green # Change to blue to switch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
