apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
    version: green
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053
