apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-green
  labels:
    app: notification-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
      version: green
  template:
    metadata:
      labels:
        app: notification-service
        version: green
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0:8080"
