apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-canary
  labels:
    app: notification-service
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: canary
  template:
    metadata:
      labels:
        app: notification-service
        version: canary
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          ports:
            - containerPort: 50053
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SERVER_ADDRESS
