apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
    version: canary
  ports:
    - name: grpc
      protocol: TCP
      port: 50030
      targetPort: 50030
    - name: http
      protocol: TCP
      port: 8030
      targetPort: 8030
    - name: swagger
      protocol: TCP
      port: 8031
      targetPort: 8031