apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-service-green
  labels:
    app: friend-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: friend-service
      version: green
  template:
    metadata:
      labels:
        app: friend-service
        version: green
    spec:
      containers:
        - name: friend-service
          image: friend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8010
            - containerPort: 8011
          env:
            - name: SERVER_GATEWAY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: SERVER_GATEWAY_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: SERVER_SWAGGER_ADDRESS
