apiVersion: v1
kind: Service
metadata:
  name: friend-service
spec:
  selector:
    app: friend-service
    version: green
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: swagger
      protocol: TCP
      port: 8091
      targetPort: 8091
