apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-service-blue
  labels:
    app: friend-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: friend-service
      version: blue
  template:
    metadata:
      labels:
        app: friend-service
        version: blue
    spec:
      containers:
        - name: friend-service
          image: friend-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0:8080"
