apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-green
  labels:
    app: profile-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-service
      version: green
  template:
    metadata:
      labels:
        app: profile-service
        version: green
    spec:
      containers:
        - name: profile-service
          image: profile-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50040
            - containerPort: 8040
            - containerPort: 8041
          env:
            - name: SERVER_GATEWAY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_GATEWAY_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_GRPC_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_SWAGGER_ADDRESS
