apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-blue
  labels:
    app: profile-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-service
      version: blue
  template:
    metadata:
      labels:
        app: profile-service
        version: blue
    spec:
      containers:
        - name: profile-service
          image: profile-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50080
            - containerPort: 9020
          env:
            - name: SERVER_HTTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_HTTP_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_GRPC_ADDRESS
