apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-green
  labels:
    app: profile-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-service
      version: green
  template:
    metadata:
      labels:
        app: profile-service
        version: green
    spec:
      containers:
        - name: profile-service
          image: profile-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50054
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: profile-service-config
                  key: SERVER_ADDRESS
