apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-blue
  labels:
    app: message-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-service
      version: blue
  template:
    metadata:
      labels:
        app: message-service
        version: blue
    spec:
      containers:
        - name: message-service
          image: message-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50052
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_ADDRESS
