apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-green
  labels:
    app: message-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-service
      version: green
  template:
    metadata:
      labels:
        app: message-service
        version: green
    spec:
      containers:
        - name: message-service
          image: message-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50060
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: SERVER_GATEWAY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_GATEWAY_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_GRPC_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_SWAGGER_ADDRESS
