apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
    version: green
  ports:
    - name: grpc
      protocol: TCP
      port: 50060
      targetPort: 50060
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
