apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
    version: green # Change to blue to switch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
