apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-blue
  labels:
    app: message-service
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-service
      version: blue
  template:
    metadata:
      labels:
        app: message-service
        version: blue
    spec:
      containers:
        - name: message-service
          image: message-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50060
            - containerPort: 9000
          env:
            - name: SERVER_HTTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_HTTP_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_GRPC_ADDRESS
