apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
    version: canary
  ports:
    - name: grpc
      protocol: TCP
      port: 50090
      targetPort: 50090
    - name: http
      protocol: TCP
      port: 9030
      targetPort: 9030
