apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-canary
  labels:
    app: search-service
    version: canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
      version: canary
  template:
    metadata:
      labels:
        app: search-service
        version: canary
    spec:
      containers:
        - name: search-service
          image: search-service:latest
          ports:
            - containerPort: 50050
            - containerPort: 8050
          env:
            - name: SERVER_HTTP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: search-service-config
                  key: SERVER_HTTP_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: search-service-config
                  key: SERVER_GRPC_ADDRESS
