apiVersion: v1
kind: Service
metadata:
  name: friend-service
spec:
  selector:
    app: friend-service
    version: green
  ports:
    - name: http
      protocol: TCP
      port: 8010
      targetPort: 8010
    - name: swagger
      protocol: TCP
      port: 8011
      targetPort: 8011
