apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-service
  labels:
    app: friend-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: friend-service
      version: canary
  template:
    metadata:
      labels:
        app: friend-service
        version: canary
    spec:
      containers:
        - name: friend-service
          image: friend-service:latest
          ports:
            - containerPort: 8010
            - containerPort: 8011
          env:
            - name: SERVER_GATEWAY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: SERVER_GATEWAY_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: SERVER_SWAGGER_ADDRESS
            - name: DB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: DB_CONNECTION_STRING
            - name: DB_MAX_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: DB_MAX_CONNECTIONS
            - name: DB_MIN_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: DB_MIN_CONNECTIONS
            - name: DB_MAX_CONN_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: DB_MAX_CONN_LIFETIME
            - name: DB_MAX_CONN_IDLE_TIME
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: DB_MAX_CONN_IDLE_TIME
            - name: DB_HEALTH_CHECK_PERIOD
              valueFrom:
                configMapKeyRef:
                  name: friend-service-config
                  key: DB_HEALTH_CHECK_PERIOD
