apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-green
  labels:
    app: search-service
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-service
      version: green
  template:
    metadata:
      labels:
        app: search-service
        version: green
    spec:
      containers:
        - name: search-service
          image: search-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: search-service-config
                  key: SERVER_ADDRESS
