apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  labels:
    app: message-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-service
      version: canary
  template:
    metadata:
      labels:
        app: message-service
        version: canary
    spec:
      containers:
        - name: message-service
          image: message-service:latest
          ports:
            - containerPort: 50020
            - containerPort: 8020
            - containerPort: 8021
          env:
            - name: SERVER_GATEWAY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_GATEWAY_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_GRPC_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: message-service-config
                  key: SERVER_SWAGGER_ADDRESS
