apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: message-service
spec:
  hosts:
    - "*"
  gateways:
    - message-service-gateway
  http:
    - route:
        - destination:
            host: message-service
            subset: stable
          weight: 90
        - destination:
            host: message-service
            subset: canary
          weight: 10
