// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/popeskul/awesome-messanger/services/auth/internal/adapters/logger"
	"github.com/popeskul/awesome-messanger/services/auth/internal/adapters/token"
	"github.com/popeskul/awesome-messanger/services/auth/internal/adapters/validator"
	"github.com/popeskul/awesome-messanger/services/auth/internal/app"
	"github.com/popeskul/awesome-messanger/services/auth/internal/config"
	"github.com/popeskul/awesome-messanger/services/auth/internal/delivery/grpc/grpc"
	"github.com/popeskul/awesome-messanger/services/auth/internal/delivery/grpc/grpc_gateway"
	"github.com/popeskul/awesome-messanger/services/auth/internal/delivery/grpc/handlers"
	"github.com/popeskul/awesome-messanger/services/auth/internal/delivery/http/swagger"
	"github.com/popeskul/awesome-messanger/services/auth/internal/usecases"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	zapLogger, err := ProvideZapLogger()
	if err != nil {
		return nil, err
	}
	portsLogger := logger.NewZapLogger(zapLogger)
	authUseCase := usecases.NewAuthUseCase(portsLogger)
	portsToken := token.NewTokenService()
	tokenUseCase := usecases.NewTokenUseCase(portsLogger, portsToken)
	v := validator.ProvideProtoMessages()
	portsValidator, err := validator.NewGrpcValidator(v...)
	if err != nil {
		return nil, err
	}
	authServiceServer := handlers.NewAuthHandler(authUseCase, tokenUseCase, portsValidator, portsLogger)
	healthHandler := handlers.NewHealthHandler()
	servicesServer := handlers.NewHandler(authServiceServer, healthHandler)
	grpcServer := grpc.NewServer(servicesServer)
	gatewayServer := grpc_gateway.NewGatewayServer(grpcServer)
	swaggerAddress := swagger.ProvideSwaggerAddress(configConfig)
	apiBaseURL := swagger.ProvideAPIBaseURL(configConfig)
	server := swagger.NewSwaggerServer(swaggerAddress, apiBaseURL)
	appApp := app.NewApp(configConfig, portsLogger, grpcServer, gatewayServer, server)
	return appApp, nil
}

// wire.go:

func ProvideZapLogger() (*zap.Logger, error) {
	logger2, err := zap.NewProduction()
	if err != nil {
		return nil, err
	}
	return logger2, nil
}
