apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
    version: canary
  ports:
    - name: grpc
      protocol: TCP
      port: 50050
      targetPort: 50050
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: swagger
      protocol: TCP
      port: 8081
      targetPort: 8081
