apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
      version: canary
  template:
    metadata:
      labels:
        app: auth-service
        version: canary
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_ADDRESS
