apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-canary
  labels:
    app: auth-service
    version: canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
      version: canary
  template:
    metadata:
      labels:
        app: auth-service
        version: canary
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          ports:
            - containerPort: 50000
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: SERVER_GATEWAY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_GATEWAY_ADDRESS
            - name: SERVER_GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_GRPC_ADDRESS
            - name: SERVER_SWAGGER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: SERVER_SWAGGER_ADDRESS
