// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/popeskul/awesome-messanger/services/message/internal/adapters/logger"
	"github.com/popeskul/awesome-messanger/services/message/internal/adapters/validator"
	"github.com/popeskul/awesome-messanger/services/message/internal/app"
	"github.com/popeskul/awesome-messanger/services/message/internal/config"
	"github.com/popeskul/awesome-messanger/services/message/internal/delivery/grpc/gateway"
	"github.com/popeskul/awesome-messanger/services/message/internal/delivery/grpc/handlers"
	"github.com/popeskul/awesome-messanger/services/message/internal/delivery/grpc/server"
	"github.com/popeskul/awesome-messanger/services/message/internal/delivery/http/swagger"
	"github.com/popeskul/awesome-messanger/services/message/internal/usecases"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	zapLogger, err := ProvideZapLogger()
	if err != nil {
		return nil, err
	}
	portsLogger := logger.NewZapLogger(zapLogger)
	messageUseCase := usecases.NewMessageUseCase(portsLogger)
	v := validator.ProvideProtoMessages()
	portsValidator, err := validator.NewGrpcValidator(v...)
	if err != nil {
		return nil, err
	}
	messageHandler := handlers.NewMessageHandler(messageUseCase, portsValidator, portsLogger)
	healthHandler := handlers.NewHealthHandler()
	servicesServer := handlers.NewHandler(messageHandler, healthHandler)
	grpcServer := server.NewGrpcServer(servicesServer)
	gatewayServer := gateway.NewGatewayServer(grpcServer)
	swaggerAddress := swagger.ProvideSwaggerAddress(configConfig)
	apiBaseURL := swagger.ProvideAPIBaseURL(configConfig)
	swaggerServer := swagger.NewSwaggerServer(swaggerAddress, apiBaseURL)
	appApp := app.NewApp(configConfig, portsLogger, grpcServer, gatewayServer, swaggerServer)
	return appApp, nil
}

// wire.go:

func ProvideZapLogger() (*zap.Logger, error) {
	logger2, err := zap.NewProduction()
	if err != nil {
		return nil, err
	}
	return logger2, nil
}
